### ISSUE TITLE
Consider automating the update of "Structure of the Community Vault" IN CONTRIBUTING

### ISSUE THREAD

**Issue by claremacrae** [obsidian-community/obsidian-hub#281]
_This is separated out from #153_

The tree in "[Structure of the Community Vault](https://publish.obsidian.md/hub/CONTRIBUTING#Structure+of+the+Community+Vault)" IN CONTRIBUTING could be populated automatically, for when directories are added or renamed.

- The comments in the source file show the tree command-line args
- There could be a script which ran the tree command automatically, and saved the output to a file
- That file could then be ![[]] embedded inside the CONTRIBUTING page

**Comment by lguenth** [comment]
Hi Clare,
I had a go at this over on this branch in my fork: https://github.com/lguenth/obsidian-hub/commits/update-tree-structure

I've never set up any workflows and I'm not quite sure how to test whether that YAML file actually does what I want. I also just guessed where to put the generated file (putting it next to the Structure note seemed fitting).

It would be great if anyone could take a look at it since this is (in my opinion) not ready for a PR yet and I also seem to be having an issue with creating PRs (see my last two) the right way in general. :sweat_smile:

**Comment by claremacrae** [comment]
@lguenth Hi Luke, this is great, thank you very much.

From an initial look at what you did, it all looks really good.

**GitHub Action**

Since I create this issue, we now have a GitHub Action that does an increasingly long list of automated changes:

https://github.com/obsidian-community/obsidian-hub/blob/main/.github/workflows/update_hub.yml

So I think it would be good to add your new script as a new block in that file, rather than creating a whole separate file.

**Creating PRs**

I'd love to help. Can you tell me anything about the problems you had, or point me to a previous one?

**Comment by lguenth** [comment]
@claremacrae 
Thanks for the reply! I will incorporate the script into update_hub tomorrow, which makes much more sense! :)

The PR(s) I was referring to are #292 and #293. Although I created two separate branches, I somehow ended up with commits from each of them in the other, non-related PR. If you could take a look at one of them, I would really appreciate it. We can also discuss that one Discord, of course.
I just don't want to make the same mistake again in the future. I'm very new to actively contributing on Github.

**Comment by claremacrae** [comment]
@lguenth thank you...

I've started replying in https://github.com/obsidian-community/obsidian-hub/pull/293
