### ISSUE TITLE
Plugin/Theme submission guides also need updating for removal of branch from community plugins/themes.

### ISSUE THREAD

**Issue by joethei** [obsidian-community/obsidian-hub#616]
The branch parameter is no longer used inside of Obsidian when downloading community plugins/themes.

The following pages are therefore outdated.
- <https://publish.obsidian.md/hub/04+-+Guides%2C+Workflows%2C+%26+Courses/Guides/How+to+add+your+plugin+to+the+community+plugin+list>
- <https://publish.obsidian.md/hub/04+-+Guides%2C+Workflows%2C+%26+Courses/Guides/How+to+add+your+theme+to+the+community+theme+store>

**Comment by claremacrae** [comment]
Hi @joethei,

Thank you.

The removal of the branch parameter is a bigger problem than that for the Hub:

- #609
- #536

It used to be possible to run the hub scripts without needing the GitHub API to be set up on contributor machines, but as I understand it, to get the default branch from a vault, one needs an access token to be set up, in order to run these scripts locally and develop them, and update them for breakages caused by the branch removal.

(I do understand why it was removed from the community plugins/themes - it has just had consequences for the Hub).

**Comment by joethei** [comment]
I've got an easy solution for those two, replace all usages of the branch with `HEAD` in GitHub urls.
If we use the theme screenshot example:
- won't work <https://github.com/ThisTheThe/MicroMike/raw/master/screenshotThumb.png>
- will work <https://github.com/ThisTheThe/MicroMike/raw/HEAD/screenshotThumb.png>

**Comment by claremacrae** [comment]
> I've got an easy solution for those two, replace all usages of the branch with `HEAD` in GitHub urls. Eg if we use the theme screenshot example:
> 
> * won't work https://github.com/ThisTheThe/MicroMike/raw/master/screenshotThumb.png
> * will work https://github.com/ThisTheThe/MicroMike/raw/HEAD/screenshotThumb.png

Oh wow - thank you very much indeed! ❤️ 🎉 🤣

**Comment by joethei** [comment]
Looks like this was done
